  version: '3.8'

  services:
    linkloom-backend:
      build: .
      environment:
        - MONGODB_URI=mongodb+srv://shamilchennara84:jky40TFnibZ50gjT@cluster0.dsvgq5l.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
        - JWT_SECRET_KEY=jwtsecretabc
        - PORT=3000
        - CORS_URI=https://linkloomfront.vercel.app/
        - EMAIL=linkloom789@gmail.com
        - PASSWORD=tuhkxtvpynnwmpdu
      volumes:
        - .:/app
      working_dir: /app
      command: npm run start