version: '3.8'

services:
  node:
    build:
      context: ./
      dockerfile: ./.docker/node.Dockerfile
    environment:
      - MONGODB_URI=mongodb+srv://shamilchennara84:jky40TFnibZ50gjT@cluster0.dsvgq5l.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET_KEY=jwtsecretabc
      - PORT=3000
      - CORS_URI=https://linkloomfront.vercel.app/
      - EMAIL=linkloom789@gmail.com
      - PASSWORD=tuhkxtvpynnwmpdu
      - DOCKER_NGINX_NODE_HOST=fun-with-docker-node
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 2

  nginx:
    build:
      context: ./
      dockerfile: ./.docker/nginx.Dockerfile
    restart: unless-stopped  
    volumes:
      - nginx-config:/etc/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - node
    entrypoint: /bin/sh -c "apk update && apk add certbot python3-certbot-nginx && certbot --nginx -d yourdomain.com && nginx -g 'daemon off;'"

volumes:
  nginx-config:
