version: '3.8'

services:
 linkloom-backend:
    build: .
    environment:
      - MONGODB_URI=mongodb://mongo:27017/linkloom
      - JWT_SECRET_KEY=jwtsecretabc
      - PORT=3000
      - CORS_URI=http://localhost:4200
      - EMAIL=linkloom789@gmail.com
      - PASSWORD=tuhkxtvpynnwmpdu
    volumes:
      - .:/app
    working_dir: /app
    command: npm run start
    depends_on:
      - mongo

 mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    container_name: mongo_container

 nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      - linkloom-backend

volumes:
 mongo-data: